services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    network_mode: host
    ipc: host
    privileged: true

    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=/run/user/1001
      - PIPEWIRE_RUNTIME_DIR=/run/user/1001
      
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd

    volumes:
      - ./rogsthumble_ws:/root/rogsthumble_ws:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/gabrielt/.Xauthority:/root/.Xauthority:ro
      - /run/user/1001:/run/user/1001:rw
      
    command: sleep infinity